#!/usr/bin/env node
/**
 * generate-blocks.mjs — build .claude/blocks.json for a product repo.
 *
 * Blocks are the feature directories under src/components/ (depth 1) plus the
 * children of any "dashboard-like" dir (a depth-1 dir where 3+ children carry
 * their own README.md — e.g. hogwarts' school-dashboard/). Each block keyword
 * maps to its path, its context records (README.md / ISSUE.md / CLAUDE.md that
 * exist), and its docs pages (<block>.mdx under content/docs-en|docs-ar|docs).
 *
 * The registry powers the block protocol hooks (~/.claude/hooks/block-*.sh):
 * read records + related GitHub issue before work, update them after.
 *
 * Usage: node generate-blocks.mjs <repo-root>
 */
import { existsSync, readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative } from "node:path";

const root = process.argv[2];
if (!root || !existsSync(join(root, "src/components"))) {
  console.error("usage: generate-blocks.mjs <repo-root>  (must contain src/components)");
  process.exit(1);
}

const CONTEXT_FILES = ["README.md", "ISSUE.md", "CLAUDE.md"];
const DOCS_DIRS = ["content/docs-en", "content/docs-ar", "content/docs"].filter((d) =>
  existsSync(join(root, d))
);

const dirsOf = (p) =>
  readdirSync(join(root, p))
    .filter((n) => !n.startsWith(".") && !n.startsWith("_"))
    .filter((n) => statSync(join(root, p, n)).isDirectory());

const contextOf = (p) => CONTEXT_FILES.filter((f) => existsSync(join(root, p, f)));
const docsOf = (name) =>
  DOCS_DIRS.map((d) => `${d}/${name}.mdx`).filter((f) => existsSync(join(root, f)));

// Collect candidate blocks: depth-1 dirs, plus children of dashboard-like dirs.
const candidates = [];
for (const name of dirsOf("src/components")) {
  const path = `src/components/${name}`;
  candidates.push({ name, path });
  const children = dirsOf(path);
  const dashboardLike = children.filter((c) => contextOf(`${path}/${c}`).includes("README.md"));
  if (dashboardLike.length >= 3) {
    for (const c of children) candidates.push({ name: c, path: `${path}/${c}` });
  }
}

// Resolve keyword collisions: most context records wins; tie → deeper path
// (the dashboard feature, which is what "optimize <block>" usually means).
const blocks = {};
for (const { name, path } of candidates) {
  const entry = { path, context: contextOf(path), docs: docsOf(name) };
  const prev = blocks[name];
  if (
    !prev ||
    entry.context.length > prev.context.length ||
    (entry.context.length === prev.context.length && path.split("/").length > prev.path.split("/").length)
  ) {
    blocks[name] = entry;
  }
}

const sorted = Object.fromEntries(Object.entries(blocks).sort(([a], [b]) => a.localeCompare(b)));
const out = {
  description:
    "Block keyword registry — generated by kun/.claude/scripts/generate-blocks.mjs. Powers the block protocol hooks: read context + related GitHub issue before work, update records + docs after.",
  docsDirs: DOCS_DIRS,
  blocks: sorted,
};

mkdirSync(join(root, ".claude"), { recursive: true });
const target = join(root, ".claude/blocks.json");
writeFileSync(target, JSON.stringify(out, null, 2) + "\n");
console.log(
  `${relative(process.cwd(), target)}: ${Object.keys(sorted).length} blocks (` +
    `${Object.values(sorted).filter((b) => b.context.length).length} with records, ` +
    `${Object.values(sorted).filter((b) => b.docs.length).length} with docs)`
);
