#!/bin/bash
# Setup secrets from private GitHub gist
# Usage: curl -fsSL https://raw.githubusercontent.com/databayt/codebase/main/.claude/scripts/secrets.sh | bash -s -- <GIST_ID>

set -e

GIST_ID="${1:-}"
CLAUDE_DIR="$HOME/.claude"
ENV_FILE="$CLAUDE_DIR/.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== Claude Code Secrets Setup ===${NC}"
echo ""

# Check for gist ID
if [ -z "$GIST_ID" ]; then
    echo -e "${RED}Error: Gist ID required${NC}"
    echo ""
    echo "Usage:"
    echo "  ~/.claude/scripts/secrets.sh <GIST_ID>"
    echo ""
    echo "Or with curl:"
    echo "  curl -fsSL https://raw.githubusercontent.com/databayt/codebase/main/.claude/scripts/secrets.sh | bash -s -- <GIST_ID>"
    echo ""
    echo "Get the Gist ID from your team lead."
    exit 1
fi

# Ensure claude directory exists
mkdir -p "$CLAUDE_DIR"

# Fetch secrets from gist
echo -e "${YELLOW}Fetching secrets from gist...${NC}"
GIST_URL="https://gist.githubusercontent.com/raw/$GIST_ID"

# Try to fetch the gist
SECRETS=$(curl -fsSL "$GIST_URL" 2>/dev/null) || {
    echo -e "${RED}Error: Could not fetch gist. Check the ID and try again.${NC}"
    exit 1
}

# Validate JSON
if ! echo "$SECRETS" | python3 -c "import sys, json; json.load(sys.stdin)" 2>/dev/null; then
    echo -e "${RED}Error: Invalid JSON in gist${NC}"
    exit 1
fi

echo -e "${GREEN}Secrets fetched successfully${NC}"
echo ""

# Extract and write environment variables
echo -e "${YELLOW}Writing environment file...${NC}"

# Create .env file
cat > "$ENV_FILE" << 'HEADER'
# Claude Code Environment Variables
# Auto-generated by secrets.sh
# DO NOT COMMIT THIS FILE

HEADER

# Parse all sections from the gist
echo "$SECRETS" | python3 -c "
import sys, json
data = json.load(sys.stdin)

# Section order for .env file
sections = [
    ('required', 'Required'),
    ('databases', 'Databases'),
    ('ai', 'AI'),
    ('auth', 'Auth'),
    ('services', 'Services'),
    ('cloudinary', 'Cloudinary'),
    ('imagekit', 'ImageKit'),
    ('telegram', 'Telegram'),
    ('optional', 'Optional')
]

for section_key, section_name in sections:
    section = data.get(section_key, {})
    if section:
        has_values = any(v and not str(v).startswith('ghp_xxx') and not str(v).startswith('neon_api_xxx') and 'GET_FROM' not in str(v) for v in section.values())
        if has_values:
            print(f'# {section_name}')
            for key, value in section.items():
                if value and not str(value).startswith('ghp_xxx') and not str(value).startswith('neon_api_xxx') and 'GET_FROM' not in str(value):
                    print(f'{key}={value}')
            print()
" >> "$ENV_FILE"

# Set permissions
chmod 600 "$ENV_FILE"

echo -e "${GREEN}Environment file created: $ENV_FILE${NC}"
echo ""

# Add to shell profile
SHELL_RC="$HOME/.zshrc"
[ -f "$HOME/.bashrc" ] && SHELL_RC="$HOME/.bashrc"

EXPORT_LINE='[ -f "$HOME/.claude/.env" ] && export $(grep -v "^#" "$HOME/.claude/.env" | xargs)'

if ! grep -q ".claude/.env" "$SHELL_RC" 2>/dev/null; then
    echo "" >> "$SHELL_RC"
    echo "# Claude Code secrets" >> "$SHELL_RC"
    echo "$EXPORT_LINE" >> "$SHELL_RC"
    echo -e "${GREEN}Added auto-load to $SHELL_RC${NC}"
fi

# Load now
export $(grep -v "^#" "$ENV_FILE" | xargs) 2>/dev/null

echo ""
echo -e "${GREEN}=== Setup Complete ===${NC}"
echo ""
echo "Secrets are now configured. Either:"
echo "  1. Restart your terminal"
echo "  2. Run: source $SHELL_RC"
echo ""
echo "Then run 'claude' to start."
