# Setup secrets from private GitHub gist (Windows PowerShell)
# Usage: & "$env:USERPROFILE\.claude\scripts\setup-secrets.ps1" -GistId "<GIST_ID>"
# Or: irm https://raw.githubusercontent.com/databayt/codebase/main/.claude/scripts/setup-secrets.ps1 | iex; Setup-Secrets -GistId "<GIST_ID>"

param(
    [Parameter(Mandatory=$false)]
    [string]$GistId
)

$ErrorActionPreference = "Stop"

$ClaudeDir = "$env:USERPROFILE\.claude"
$EnvFile = "$ClaudeDir\.env"

Write-Host "=== Claude Code Secrets Setup ===" -ForegroundColor Cyan
Write-Host ""

# Check for gist ID
if (-not $GistId) {
    Write-Host "Error: Gist ID required" -ForegroundColor Red
    Write-Host ""
    Write-Host "Usage:"
    Write-Host "  .\setup-secrets.ps1 -GistId <GIST_ID>"
    Write-Host ""
    Write-Host "Get the Gist ID from your team lead."
    exit 1
}

# Ensure claude directory exists
if (-not (Test-Path $ClaudeDir)) {
    New-Item -ItemType Directory -Path $ClaudeDir -Force | Out-Null
}

# Fetch secrets from gist
Write-Host "Fetching secrets from gist..." -ForegroundColor Yellow
$GistUrl = "https://gist.githubusercontent.com/raw/$GistId"

try {
    $Secrets = Invoke-RestMethod -Uri $GistUrl
} catch {
    Write-Host "Error: Could not fetch gist. Check the ID and try again." -ForegroundColor Red
    exit 1
}

Write-Host "Secrets fetched successfully" -ForegroundColor Green
Write-Host ""

# Write environment file
Write-Host "Writing environment file..." -ForegroundColor Yellow

$EnvContent = @"
# Claude Code Environment Variables
# Auto-generated by setup-secrets.ps1
# DO NOT COMMIT THIS FILE

# Required
"@

foreach ($key in $Secrets.required.PSObject.Properties.Name) {
    $value = $Secrets.required.$key
    if ($value -and -not $value.StartsWith("ghp_xxx") -and -not $value.StartsWith("neon_api_xxx")) {
        $EnvContent += "`n$key=$value"
    }
}

$EnvContent += "`n`n# Optional"

foreach ($key in $Secrets.optional.PSObject.Properties.Name) {
    $value = $Secrets.optional.$key
    if ($value) {
        $EnvContent += "`n$key=$value"
    }
}

$EnvContent | Out-File -FilePath $EnvFile -Encoding UTF8

Write-Host "Environment file created: $EnvFile" -ForegroundColor Green
Write-Host ""

# Add to PowerShell profile
$ProfileDir = Split-Path $PROFILE
if (-not (Test-Path $ProfileDir)) {
    New-Item -ItemType Directory -Path $ProfileDir -Force | Out-Null
}

$ProfileContent = @'

# Claude Code secrets
if (Test-Path "$env:USERPROFILE\.claude\.env") {
    Get-Content "$env:USERPROFILE\.claude\.env" | ForEach-Object {
        if ($_ -and -not $_.StartsWith("#")) {
            $parts = $_ -split "=", 2
            if ($parts.Length -eq 2) {
                [Environment]::SetEnvironmentVariable($parts[0], $parts[1], "Process")
            }
        }
    }
}
'@

if (-not (Test-Path $PROFILE) -or -not (Select-String -Path $PROFILE -Pattern "claude.*\.env" -Quiet)) {
    Add-Content -Path $PROFILE -Value $ProfileContent
    Write-Host "Added auto-load to PowerShell profile" -ForegroundColor Green
}

# Load now
Get-Content $EnvFile | ForEach-Object {
    if ($_ -and -not $_.StartsWith("#")) {
        $parts = $_ -split "=", 2
        if ($parts.Length -eq 2) {
            [Environment]::SetEnvironmentVariable($parts[0], $parts[1], "Process")
        }
    }
}

Write-Host ""
Write-Host "=== Setup Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Secrets are now configured. Either:"
Write-Host "  1. Restart PowerShell"
Write-Host "  2. Run: . `$PROFILE"
Write-Host ""
Write-Host "Then run 'claude' to start."

# Function for one-liner install
function Setup-Secrets {
    param([string]$GistId)
    & "$env:USERPROFILE\.claude\scripts\setup-secrets.ps1" -GistId $GistId
}
