#!/usr/bin/env bash
# inventory.sh — Generate canonical inventory of kun's .claude/ engine state.
# Story 13.1 in docs/EPICS-V4.md.
#
# Outputs:
#   docs/INVENTORY.md                                         # human-readable
#   ~/.claude/projects/-Users-abdout-kun/memory/kun-inventory.json  # machine-readable
#
# Usage: bash scripts/inventory.sh
# Exit:  0 on success, non-zero on filesystem error.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLAUDE_DIR="${REPO_ROOT}/.claude"
DOCS_DIR="${REPO_ROOT}/docs"
MEMORY_DIR="${HOME}/.claude/projects/-Users-abdout-kun/memory"

[ -d "$CLAUDE_DIR" ] || { echo "fatal: ${CLAUDE_DIR} not found" >&2; exit 1; }
mkdir -p "$DOCS_DIR" "$MEMORY_DIR"

# --- Counts ---------------------------------------------------------------

count_files() {
  local dir="$1" pattern="${2:-*.md}"
  [ -d "$dir" ] || { echo 0; return; }
  find "$dir" -maxdepth 1 -type f -name "$pattern" 2>/dev/null | wc -l | tr -d ' '
}

count_dirs() {
  local dir="$1"
  [ -d "$dir" ] || { echo 0; return; }
  find "$dir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' '
}

agents_count="$(count_files "$CLAUDE_DIR/agents" "*.md")"
commands_count="$(count_files "$CLAUDE_DIR/commands" "*.md")"
rules_count="$(count_files "$CLAUDE_DIR/rules" "*.md")"
skills_count="$(count_dirs "$CLAUDE_DIR/skills")"
patterns_count="$(count_files "$CLAUDE_DIR/patterns/cards" "*.md")"
memory_json_count="$(find "$CLAUDE_DIR/memory" -maxdepth 1 -type f -name '*.json' 2>/dev/null | wc -l | tr -d ' ')"
memory_md_count="$(find "$CLAUDE_DIR/memory" -maxdepth 1 -type f -name '*.md' 2>/dev/null | wc -l | tr -d ' ')"
auto_memory_count="$(find "$MEMORY_DIR" -maxdepth 1 -type f \( -name '*.md' -o -name '*.json' \) 2>/dev/null | wc -l | tr -d ' ')"

mcp_servers_count=0
if [ -f "$CLAUDE_DIR/mcp.json" ] && command -v jq >/dev/null 2>&1; then
  mcp_servers_count="$(jq -r '.mcpServers | keys | length' "$CLAUDE_DIR/mcp.json" 2>/dev/null || echo 0)"
fi

mcp_variants=0
for variant in mcp-business.json mcp-content.json mcp-ops.json; do
  [ -f "$CLAUDE_DIR/$variant" ] && mcp_variants=$((mcp_variants + 1))
done

hooks_count=0
allow_count=0
deny_count=0
if [ -f "$CLAUDE_DIR/settings.json" ] && command -v jq >/dev/null 2>&1; then
  hooks_count="$(jq -r '[.hooks // {} | to_entries[] | .value | length] | add // 0' "$CLAUDE_DIR/settings.json" 2>/dev/null || echo 0)"
  allow_count="$(jq -r '.permissions.allow // [] | length' "$CLAUDE_DIR/settings.json" 2>/dev/null || echo 0)"
  deny_count="$(jq -r '.permissions.deny // [] | length' "$CLAUDE_DIR/settings.json" 2>/dev/null || echo 0)"
fi

# --- Drift detection ------------------------------------------------------

# Phantom rules — declared in v3 EPICS but never written
phantom_rules=()
for rule in auth i18n prisma tailwind testing deployment multi-repo org-refs; do
  [ -f "$CLAUDE_DIR/rules/${rule}.md" ] || phantom_rules+=("$rule")
done

# Phantom memory files — declared in v3 EPICS but never written
phantom_memory=()
for mem in preferences atom template block report captain-state runway revenue capacity pilot-king-fahad; do
  [ -f "$CLAUDE_DIR/memory/${mem}.json" ] || phantom_memory+=("${mem}.json")
done
[ -f "${HOME}/.claude/bridge.md" ] || phantom_memory+=("~/.claude/bridge.md")

# --- INVENTORY.md ---------------------------------------------------------

generated_at="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
out="$DOCS_DIR/INVENTORY.md"

{
  echo "# Kun Engine Inventory"
  echo
  echo "> Auto-generated by \`scripts/inventory.sh\`. Do not edit by hand — re-run the script."
  echo "> Generated: ${generated_at}"
  echo
  echo "## Counts"
  echo
  echo "| Surface | Count | v3 doc claim | Status |"
  echo "|---------|------:|------------:|--------|"
  echo "| Agents (\`.claude/agents/*.md\`) | ${agents_count} | 28 | $([ "$agents_count" -ge 28 ] && echo Underclaim || echo Drift) |"
  echo "| Commands (\`.claude/commands/*.md\`) | ${commands_count} | 17 | $([ "$commands_count" -ge 17 ] && echo Underclaim || echo Drift) |"
  echo "| Skills v2 (\`.claude/skills/<dir>/SKILL.md\`) | ${skills_count} | — | E20 migration in progress |"
  echo "| MCP servers in \`mcp.json\` | ${mcp_servers_count} | 18 | $([ "$mcp_servers_count" -ge 18 ] && echo Underclaim || echo Drift) |"
  echo "| MCP role variants | ${mcp_variants} | 3 | $([ "$mcp_variants" -ge 3 ] && echo Match || echo Missing) |"
  echo "| Rules (\`.claude/rules/*.md\`) | ${rules_count} | 8 | $([ "$rules_count" -ge 8 ] && echo Match || echo "Phantom — see E14") |"
  echo "| Memory JSON (\`.claude/memory/*.json\`) | ${memory_json_count} | 6 | $([ "$memory_json_count" -ge 6 ] && echo Match || echo "Phantom — see E14") |"
  echo "| Memory MD (\`.claude/memory/*.md\`) | ${memory_md_count} | 0 | informational |"
  echo "| Auto-memory files (\`~/.claude/projects/-Users-abdout-kun/memory/\`) | ${auto_memory_count} | — | informational |"
  echo "| Pattern cards | ${patterns_count} | 10 | $([ "$patterns_count" -ge 10 ] && echo Match || echo Drift) |"
  echo "| Hooks wired in \`settings.json\` | ${hooks_count} | 5 | $([ "$hooks_count" -ge 5 ] && echo Match || echo "Partial — see E15.4") |"
  echo "| Permission allow rules | ${allow_count} | 38 | $([ "$allow_count" -ge 38 ] && echo Match || echo "Phantom — see E15.1") |"
  echo "| Permission deny rules | ${deny_count} | 4 | $([ "$deny_count" -ge 4 ] && echo Match || echo "Phantom — see E15.2") |"
  echo
  if [ ${#phantom_rules[@]} -gt 0 ]; then
    echo "## Missing rules (E14 backfill)"
    echo
    for r in "${phantom_rules[@]}"; do
      echo "- \`.claude/rules/${r}.md\` — declared in v3 EPICS, not present"
    done
    echo
  fi
  if [ ${#phantom_memory[@]} -gt 0 ]; then
    echo "## Missing memory (E14 backfill)"
    echo
    for m in "${phantom_memory[@]}"; do
      echo "- \`${m}\` — declared in v3 EPICS, not present"
    done
    echo
  fi
  echo "## Agents"
  echo
  if [ -d "$CLAUDE_DIR/agents" ]; then
    find "$CLAUDE_DIR/agents" -maxdepth 1 -type f -name '*.md' \
      | sort | while read -r f; do
      name="$(basename "$f" .md)"
      lines="$(wc -l <"$f" | tr -d ' ')"
      echo "- \`${name}\` (${lines} lines)"
    done
  fi
  echo
  echo "## Commands"
  echo
  if [ -d "$CLAUDE_DIR/commands" ]; then
    find "$CLAUDE_DIR/commands" -maxdepth 1 -type f -name '*.md' \
      | sort | while read -r f; do
      echo "- \`/$(basename "$f" .md)\`"
    done
  fi
  echo
  echo "## Rules"
  echo
  if [ -d "$CLAUDE_DIR/rules" ]; then
    find "$CLAUDE_DIR/rules" -maxdepth 1 -type f -name '*.md' \
      | sort | while read -r f; do
      echo "- \`$(basename "$f")\`"
    done
  fi
  echo
  echo "## Memory"
  echo
  if [ -d "$CLAUDE_DIR/memory" ]; then
    find "$CLAUDE_DIR/memory" -maxdepth 1 -type f \
      | sort | while read -r f; do
      bytes="$(wc -c <"$f" | tr -d ' ')"
      echo "- \`$(basename "$f")\` (${bytes} bytes)"
    done
  fi
  echo
  echo "## MCP servers"
  echo
  if [ -f "$CLAUDE_DIR/mcp.json" ] && command -v jq >/dev/null 2>&1; then
    jq -r '.mcpServers | keys[] | "- `\(.)`"' "$CLAUDE_DIR/mcp.json" 2>/dev/null || true
  fi
  echo
} > "$out"

# --- kun-inventory.json (machine-readable) --------------------------------

mem_out="${MEMORY_DIR}/kun-inventory.json"

if command -v jq >/dev/null 2>&1; then
  jq -n \
    --arg generated_at "$generated_at" \
    --argjson agents "$agents_count" \
    --argjson commands "$commands_count" \
    --argjson skills "$skills_count" \
    --argjson rules "$rules_count" \
    --argjson memory_json "$memory_json_count" \
    --argjson memory_md "$memory_md_count" \
    --argjson auto_memory "$auto_memory_count" \
    --argjson patterns "$patterns_count" \
    --argjson mcp_servers "$mcp_servers_count" \
    --argjson mcp_variants "$mcp_variants" \
    --argjson hooks "$hooks_count" \
    --argjson allow_rules "$allow_count" \
    --argjson deny_rules "$deny_count" \
    --argjson phantom_rules "$(if [ ${#phantom_rules[@]} -gt 0 ]; then printf '%s\n' "${phantom_rules[@]}" | jq -R . | jq -s .; else echo '[]'; fi)" \
    --argjson phantom_memory "$(if [ ${#phantom_memory[@]} -gt 0 ]; then printf '%s\n' "${phantom_memory[@]}" | jq -R . | jq -s .; else echo '[]'; fi)" \
    '{
      generated_at: $generated_at,
      counts: {
        agents: $agents,
        commands: $commands,
        skills: $skills,
        rules: $rules,
        memory_json: $memory_json,
        memory_md: $memory_md,
        auto_memory: $auto_memory,
        patterns: $patterns,
        mcp_servers: $mcp_servers,
        mcp_variants: $mcp_variants,
        hooks: $hooks,
        allow_rules: $allow_rules,
        deny_rules: $deny_rules
      },
      phantom: {
        rules: $phantom_rules,
        memory: $phantom_memory
      }
    }' > "$mem_out"
fi

echo "Wrote: $out"
echo "Wrote: $mem_out"

# Also write to in-repo memory so the docs site (and CI) can read at build time.
in_repo_mem="${CLAUDE_DIR}/memory/kun-inventory.json"
if [ -f "$mem_out" ]; then
  cp "$mem_out" "$in_repo_mem"
  echo "Wrote: $in_repo_mem"
fi
echo
echo "Counts: agents=$agents_count commands=$commands_count rules=$rules_count memory=$memory_json_count mcp=$mcp_servers_count hooks=$hooks_count allow=$allow_count deny=$deny_count"
if [ ${#phantom_rules[@]+x} ] && [ ${#phantom_rules[@]} -gt 0 ]; then
  echo "Phantom rules: ${phantom_rules[*]}"
fi
if [ ${#phantom_memory[@]+x} ] && [ ${#phantom_memory[@]} -gt 0 ]; then
  echo "Phantom memory: ${phantom_memory[*]}"
fi
exit 0
